### ISSUE TITLE
The names of the logfiles are not passed to syslog

### ISSUE THREAD

**Issue by KaiHofstetter** [cloudfoundry/blackbox#5]
## Current behaviour
All log files found below the configured `source_dir:` folder are passed to the syslog server.
The directory name below `source_dir:` is passed as the `app-name` in the syslog protocol.

https://github.com/cloudfoundry/blackbox/blob/7a03185f289fe3f0d611c3cb09af5ff0f3ba7eb7/file_watcher.go#L104

**The name of the log files is not passed to the syslog server!**

## Issue
Very often there are several different log files, with different semantics and sometimes even different format. Since the log file name is lost, it is hard the filter specific log files or use different log parsers.

## Possible solution
One possible solution could be to pass the relative folder name, including the file name in the syslog `app-name` field.

#### Blackbox configuration:
```
syslog:
...
    source_dir: /var/vcap/sys/log/
```

#### Log files:
```
/var/vcap/sys/log/director/access.log
/var/vcap/sys/log/director/director.stdout.log
/var/vcap/sys/log/director/director.error.log
...
```

### Passed app-name values
```
director/access.log
director/director.stdout.log
director/director.error.log
...
```

If the current behaviour should not change by default, the new behaviour could be configurable.

Should we create a PR?

**Comment by anEXPer** [comment]
We'd take a PR to do this by default. It should be disable-able, but I think it's a preferable default behavior.

This repo is basically just for use in `syslog-release`. I'll have to be a little more careful about rolling out changes to cf logging, so I need the option to turn it off for a while.

Thanks for noting this problem - it's definitely on the list of things I'd love to see fixed.

**Comment by BeckerMax** [comment]
@anEXPer We opened PRs for both Blackbox and the syslog forwarder release to include this functionality. We decided to not enable it by default but introduce an additional parameter to not break existing parsing rules.
