### ISSUE TITLE
Log File Naming

### ISSUE THREAD

**Issue by fbys294** [cloudfoundry/blackbox#6]
Blackbox assumes that all your logs are ".log". In some cases that's not true. Could you add a PR to pass a logprefix as a variable from the yaml. 

example yaml:
    syslog:
      address: 10.244.9.5
      transport: tcp
      blackbox:
        log_prefix: ap_log

**Comment by geofffranks** [comment]
hey @fbys294 - sorry it's taken so long for anyone to get back to you on this. Is this still an issue for you? The code still looks  at '.log' for the file suffix, I'm not sure if having most bosh jobs move to BPM resulted in log files ending in `.log` and making the issue go away.

**Comment by geofffranks** [comment]
Closing due to lack of response and age of the issue, but feel free to re-open or open a new issue if this is  still a thing for you
